/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop_181080200213;

import java.awt.print.PageFormat;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.AttributeSet;
import javax.print.attribute.HashPrintServiceAttributeSet;
import javax.print.attribute.standard.PrinterName;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author ROBBY
 */
public class Input_form_181080200213 extends javax.swing.JInternalFrame {
    private Connection conn;
    private ResultSet result;
    Winiconn_181080200213 connectpsql = new Winiconn_181080200213();
    PreparedStatement ket=null;

    /**
     * Creates new form Input_form_181080200213
     */
    public Input_form_181080200213() {
        initComponents();
        conn=connectpsql.getConnection();
        Combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_save = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nm_brg = new javax.swing.JTextField();
        kd_brg = new javax.swing.JTextField();
        hrg_sat = new javax.swing.JTextField();
        cbxitem = new javax.swing.JComboBox<>();
        btn_preview = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_close.setText("CLOSE");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INPUT DATA");

        jLabel1.setText("Kode Barang");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Kode Satuan");

        jLabel5.setText("Harga Satuan");

        nm_brg.setText("Nama Barang");

        kd_brg.setText("Kode Barang");

        hrg_sat.setText("Harga Satuan");

        cbxitem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxitem.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbxitemPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbxitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxitemActionPerformed(evt);
            }
        });

        btn_preview.setText("PREVIEW");
        btn_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previewActionPerformed(evt);
            }
        });

        btn_print.setText("PRINT");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxitem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nm_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hrg_sat, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nm_brg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hrg_sat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        kd_brg.setText("");
        kd_brg.grabFocus();
        nm_brg.setText("");
        hrg_sat.setText("");
        
    }//GEN-LAST:event_btn_addActionPerformed
    
    private void Combobox() {
        cbxitem.removeAllItems();
        String mItem, mKey;
        try {
            final Statement state = this.conn.createStatement();
            this.result = state.executeQuery("select * from satuan order by kd_sat");
            while (this.result.next()) {
                this.cbxitem.addItem(this.result.getString("kd_sat"));
            }
        }
        catch (Exception ex) {
        }
    }
    
    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        //System.exit(0);
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        if(kd_brg.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kode Barang Harus diisi");
            return;
        }else if (nm_brg.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nama Barang Harus diisi");
            return;
        }else if (hrg_sat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harga Barang harus diisi");
        }else{
            try {
                Statement s = conn.createStatement();
                result = s.executeQuery("select kd_brg from barang where kd_brg='" + kd_brg.getText()+"'");
                if (result.next()) {
                    s.execute("update barang set kd_brg='" + kd_brg.getText() +"', nm_brg= ' " +nm_brg.getText() + cbxitem.getSelectedItem().toString() +"', kd_sat= ' "  + hrg_sat.getText() +"', hrg_satuan= ' " + "'where kd_brg='" + kd_brg.getText()+"'");
                    JOptionPane.showMessageDialog(null,"Data telah terupdate");
                }else{
                    s.execute("insert into barang (kd_brg, nm_brg, kd_sat, hrg_satuan)" + "values('"+ kd_brg.getText()+"','" + nm_brg.getText()+ "' , '" + cbxitem.getSelectedItem().toString() + "' , '"+ hrg_sat.getText()+"')");
                    JOptionPane.showMessageDialog(null, "Data Telah Tersimpan");
                }
            } catch (Exception e) {
            }
        }
        
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void cbxitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxitemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxitemActionPerformed

    private void cbxitemPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbxitemPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        //String tmp = (String)cbxitem.getSelectedItem();
        //String sql = "select * from satuan where ket_sat=?";
        //try {
            //PreparedStatement pst = conn.prepareStatement(sql);
            //pst.setString(1, tmp);
            //result=pst.executeQuery();
            //if (result.next()) {
                //String show1 = result.getString("ket_sat");
                //kd_satbrg1.setText(show1);
            //}
        //} catch (Exception e) {
        //}
    }//GEN-LAST:event_cbxitemPopupMenuWillBecomeInvisible

    private void btn_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previewActionPerformed
        // TODO add your handling code here:
        try {
            //JasperDesign jd=JRXmlLoader.load("reports\\report_uas_oop_181080200213.jrxml");
            //JasperDesign jd=JRXmlLoader.load("/reports/report_uas_oop_181080200213.jrxml");
            JasperDesign jd=JRXmlLoader.load("C:/reports/report_uas_oop_181080200213.jrxml");
            //JasperDesign jd=JRXmlLoader.load("./reports/report_uas_oop_181080200213.jrxml");
            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(jr, null,connectpsql.getConnection());
            JRViewer viewer = new JRViewer(jp);
            JDesktopPane thispane;
            thispane = (JDesktopPane) this.getRootPane().getParent().getParent();
            JInternalFrame reportframe = new JInternalFrame("Report Barang", true, true, true, true);
            reportframe.add(viewer);
            reportframe.setSize(thispane.getWidth(), thispane.getHeight());
            thispane.add(reportframe);                
            reportframe.setVisible(true);

        } catch (Exception e) {
            String conmsg = "Cant Create Report" +ex.getMessage()+" "+ex.getLocalizedMessage();
            JOptionPane.showMessageDialog(null, conmsg);
        }
    }//GEN-LAST:event_btn_previewActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        try {
            Statement state = connectpsql.getConnection().createStatement();
            result = state.executeQuery("select * from barang");
            JRResultSetDataSource resultdata = new JRResultSetDataSource(result);
            //JasperPrint jasprint = JasperFillManager.fillReport("reports\\report_uas_oop_181080200213.jasper", new HashMap(), resultdata);
            //JasperPrint jasprint = JasperFillManager.fillReport("/reports/report_uas_oop_181080200213.jasper", new HashMap(), resultdata);
            JasperPrint jasprint = JasperFillManager.fillReport("C:/reports/report_uas_oop_181080200213.jasper", new HashMap(), resultdata);
            //JasperPrint jasprint = JasperFillManager.fillReport("./reports/report_uas_oop_181080200213.jasper", new HashMap(), resultdata);
            JasperPrintManager.printReport(jasprint, true);
        } catch (Exception ex) {
            String connmsg = "Cant create report" +ex.getMessage()+" "+ex.getLocalizedMessage();
            JOptionPane.showMessageDialog(null, connmsg);
        }
    }//GEN-LAST:event_btn_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_form_181080200213.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_form_181080200213.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_form_181080200213.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_form_181080200213.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_form_181080200213().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_preview;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cbxitem;
    private javax.swing.JTextField hrg_sat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField kd_brg;
    private javax.swing.JTextField nm_brg;
    // End of variables declaration//GEN-END:variables
}
