/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop_181080200213;

import java.awt.Container;
import java.awt.print.PageFormat;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.AttributeSet;
import javax.print.attribute.HashPrintServiceAttributeSet;
import javax.print.attribute.standard.PrinterName;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ROBBY
 */
public class Input_Satuan_181080200213 extends javax.swing.JInternalFrame {
    private Connection conn;
    private ResultSet result;
    Winiconn_181080200213 connectpsql = new  Winiconn_181080200213();

    /**
     * Creates new form Input_form_181080200213
     */
    public Input_Satuan_181080200213() {
        initComponents();
        conn = connectpsql.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_save = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        satkdsat = new javax.swing.JTextField();
        satketsat = new javax.swing.JTextField();
        btn_preview = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_close.setText("CLOSE");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INPUT DATA SATUAN");

        jLabel1.setText("Kode Satuan");

        jLabel3.setText("Keterangan Satuan");

        satkdsat.setText("Kode Satuan");
        satkdsat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                satkdsatFocusLost(evt);
            }
        });

        satketsat.setText("Keterangan Satuan");

        btn_preview.setText("PREVIEW");
        btn_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previewActionPerformed(evt);
            }
        });

        btn_print.setText("PRINT");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(satkdsat)
                                    .addComponent(satketsat, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btn_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(satkdsat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(satketsat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        satkdsat.setText("");
        satkdsat.grabFocus();
        satketsat.setText("");
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        //System.exit(0);
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
         if(satkdsat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kode Satuan Harus diisi");
            return;
        }else if (satketsat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Keterangan Sauan Harus diisi");
            return;
        }else{
            try {
                Statement s = conn.createStatement();
                result = s.executeQuery("select kd_sat from satuan where kd_sat='" + satketsat.getText()+"'");
                if (result.next()) {
                    s.execute("update satuan set ket_sat='" + satketsat.getText() + "'where kd_sat='" + satkdsat.getText()+"'");
                    JOptionPane.showMessageDialog(null,"Data telah terupdate");
                }else{
                    s.execute("insert into satuan (kd_sat, ket_sat)" + "values('"+ satkdsat.getText()+"','" + satketsat.getText()+ "')");
                    JOptionPane.showMessageDialog(null, "Data Telah Tersimpan");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void satkdsatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_satkdsatFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_satkdsatFocusLost

    private void btn_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previewActionPerformed
        // TODO add your handling code here:
        //Reportsall('L');
        try {
            JRResultSetDataSource resultdata = new JRResultSetDataSource(result);
            //JasperDesign jd=JRXmlLoader.load("/./reports/reportsatuan_uas_oop_181080200213.jrxml");
            //JasperDesign jd=JRXmlLoader.load("/reports/reportsatuan_uas_oop_181080200213.jrxml");
            JasperDesign jd=JRXmlLoader.load("C:/reports/reportsatuan_uas_oop_181080200213.jrxml");
            //JasperDesign jd=JRXmlLoader.load("./reports/reportsatuan_uas_oop_181080200213.jrxml");
            JasperReport jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(jr, null,connectpsql.getConnection());
            JRViewer viewer = new JRViewer(jp);
            JDesktopPane thispane;
            thispane = (JDesktopPane) this.getRootPane().getParent().getParent();
            JInternalFrame reportframe = new JInternalFrame("Report Satuan", true, true, true, true);
            reportframe.add(viewer);
            reportframe.setSize(thispane.getWidth(), thispane.getHeight());
            thispane.add(reportframe);                
            reportframe.setVisible(true);

        } catch (Exception e) {
            String conmsg = "Cant Create Report" +ex.getMessage()+" "+ex.getLocalizedMessage();
            JOptionPane.showMessageDialog(null, conmsg);
        }
        
//        try {
//            JasperDesign jasdes = JRXmlLoader.load("./reports/reportsatuan_uas_oop_181080200213.jrxml");
//            JasperReport jasrep = JasperCompileManager.compileReport(jasdes);
//            JasperPrint jasprint = JasperFillManager.fillReport(jasrep, null, connectpsql.getConnection());
//            JasperViewer.viewReport(jasprint, false);
//            JDesktopPane thispane;
//            thispane = (JDesktopPane) this.getRootPane().getParent().getParent();
//            JRViewer viewer = new JRViewer(jasprint);
//            JInternalFrame reportframe = new JInternalFrame("Report Satuan", true, true, true, true);
//            reportframe.add(viewer);
//            reportframe.setSize(thispane.getWidth(), thispane.getHeight());
//            thispane.add(reportframe);                
//            reportframe.setVisible(true);
//        } catch (Exception e) {
//            String conmsg = "Cant Create Report" +ex.getMessage()+" "+ex.getLocalizedMessage();
//            JOptionPane.showMessageDialog(null, conmsg);
//        } 
        
    }//GEN-LAST:event_btn_previewActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        //Reportsall('P');
        try {
            Statement state = connectpsql.getConnection().createStatement();
            result = state.executeQuery("select * from satuan");
            JRResultSetDataSource resultdata = new JRResultSetDataSource(result);
            //JasperPrint jasprint = JasperFillManager.fillReport("/./reports/reportsatuan_uas_oop_181080200213.jasper", new HashMap(), resultdata);
            //JasperPrint jasprint = JasperFillManager.fillReport("/reports/reportsatuan_uas_oop_181080200213.jasper", new HashMap(), resultdata);
            JasperPrint jasprint = JasperFillManager.fillReport("C:/reports/reportsatuan_uas_oop_181080200213.jasper", new HashMap(), resultdata);
            //JasperPrint jasprint = JasperFillManager.fillReport("./reports/reportsatuan_uas_oop_181080200213.jasper", new HashMap(), resultdata);
            JasperPrintManager.printReport(jasprint, true);
        } catch (Exception ex) {
            String connmsg = "Cant create report" +ex.getMessage()+" "+ex.getLocalizedMessage();
            JOptionPane.showMessageDialog(null, connmsg);
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void TableDisplay(){
        try {
            Statement s = conn.createStatement();
            String sql = "select * from satuan";
            result = s.executeQuery(sql);
        } catch (Exception e) {
        }
    }
    
    private void Reportsall(char cetak){
        try{     
            Statement state = connectpsql.getConnection().createStatement();
            if (satkdsat.getText().trim().equals("")) {
                result = state.executeQuery("select * from satuan");
            } else {
                result = state.executeQuery("select * from satuan where kd_sat='"+satkdsat.getText()+"'");
            }            
            JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(result);
            //JasperDesign jasperPrint = JRXmlLoader.load("./reports/report_uas_oop_181080200213.jrxml");
            //JasperDesign jasperPrint = JRXmlLoader.load("./reports/report_uas_oop_181080200213.jrxml", new HashMap(), resultSetDataSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport("./reports/report_uas_oop_181080200213.jasper", new HashMap(), resultSetDataSource);
            if (cetak=='P') { // cetak ke Printer
                 //JasperPrintManager.printReport(jasperPrint, true);    
                 PrinterJob printerJob = PrinterJob.getPrinterJob();
                 PageFormat pageFormat = PrinterJob.getPrinterJob().defaultPage();
                 printerJob.defaultPage(pageFormat);
                 int selectedService = 0;
                 AttributeSet attributeSet = new HashPrintServiceAttributeSet(new PrinterName("EPSON L220", null));
                 
                 PrintService[] printService = PrintServiceLookup.lookupPrintServices(null, attributeSet);
                 try {
                     printerJob.setPrintService(printService[selectedService]);
                     
                } catch (Exception e) {
                    System.out.println(e);
                }
                
            } else { // Preview                
                /// sudah OK
//                JRViewer viewer = new JRViewer(jasperPrint);                 
//                JFrame parent;
//                parent = (JFrame)this.getRootPane().getParent().getParent().getParent().getParent().getParent().getParent();
//                parent.add(viewer);
//                viewer.setVisible(true);

                JDesktopPane thispane;
                thispane = (JDesktopPane) this.getRootPane().getParent().getParent();                
                JRViewer viewer = new JRViewer(jasperPrint);                  
                JInternalFrame reportframe = new JInternalFrame("Report Satuan", true, true, true, true);                
                reportframe.add(viewer);
                reportframe.setSize(thispane.getWidth(), thispane.getHeight());                
                thispane.add(reportframe);                
                reportframe.setVisible(true);
                
                // perintah aslinya, sudah ok
                //JasperViewer.viewReport(jasperPrint, false);                 
            }                         
        }catch(Exception ex) {
            String connectMsg = "Could not create the report " + ex.getMessage()+" "+ex.getLocalizedMessage();
            JOptionPane.showMessageDialog(this, connectMsg);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Satuan_181080200213().setVisible(true);
            }
        });
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_preview;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField satkdsat;
    private javax.swing.JTextField satketsat;
    // End of variables declaration//GEN-END:variables
}
