/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop_181080200213;

import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author ROBBY
 */
public class Menu_index extends javax.swing.JFrame {
    private Connection conn;
    private ResultSet result;
    Winiconn_181080200213 connectpsql = new  Winiconn_181080200213();
    /**
     * Creates new form Menu_index
     */
   
    public Menu_index() {
        initComponents();
        conn = connectpsql.getConnection();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        menuinput = new javax.swing.JMenu();
        inpbar = new javax.swing.JMenuItem();
        inpsat = new javax.swing.JMenuItem();
        mastrep = new javax.swing.JMenuItem();
        menusystem = new javax.swing.JMenu();
        sysexit = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM TRANSAKSI UAS PBO");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        menuinput.setText("Input Data");

        inpbar.setText("Input Barang");
        inpbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpbarActionPerformed(evt);
            }
        });
        menuinput.add(inpbar);

        inpsat.setText("Input Satuan");
        inpsat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpsatActionPerformed(evt);
            }
        });
        menuinput.add(inpsat);

        mastrep.setText("Master Report");
        mastrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mastrepActionPerformed(evt);
            }
        });
        menuinput.add(mastrep);

        jMenuBar3.add(menuinput);

        menusystem.setText("System");

        sysexit.setText("Exit");
        sysexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysexitActionPerformed(evt);
            }
        });
        menusystem.add(sysexit);

        jMenuBar3.add(menusystem);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void centeralign(JInternalFrame form){
        Dimension Desksize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = form.getSize();
        form.setLocation((Desksize.width - jInternalFrameSize.width)/2, (Desksize.height- jInternalFrameSize.height)/2);
        jDesktopPane1.add(form);        
        form.setVisible(true);
    }
    
    private void sysexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysexitActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(this, "Are You Sure To Close ?", "NOTICE", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0);
    }//GEN-LAST:event_sysexitActionPerformed
    }
        
    private void inpbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpbarActionPerformed
        // TODO add your handling code here:
        JInternalFrame frame = new Input_form_181080200213(); 
        centeralign(frame);
    }//GEN-LAST:event_inpbarActionPerformed

    private void inpsatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpsatActionPerformed
        // TODO add your handling code here:
        JInternalFrame frames = new Input_Satuan_181080200213(); 
        centeralign(frames);
    }//GEN-LAST:event_inpsatActionPerformed

    private void mastrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mastrepActionPerformed
        // TODO add your handling code here:
        JInternalFrame frames = new Reportmaster_181080200213(); 
        centeralign(frames);
    }//GEN-LAST:event_mastrepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem inpbar;
    private javax.swing.JMenuItem inpsat;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem mastrep;
    private javax.swing.JMenu menuinput;
    private javax.swing.JMenu menusystem;
    private javax.swing.JMenuItem sysexit;
    // End of variables declaration//GEN-END:variables
}
